import { invoke } from "@tauri-apps/api/core";
import type {
  AppSettings,
  BackupManifest,
  Category,
  ImportPreview,
  ImportResult,
  Note,
  OrganizerResult,
  SaveNoteInput,
  SaveNoteResponse,
  SearchHistoryItem,
  SearchQuery,
  SearchResult,
  Tag,
} from "../types";

export const api = {
  listNotes: (view = "all", limit = 500) => invoke<Note[]>("list_notes", { view, limit }),
  getNote: (id: string) => invoke<Note>("get_note", { id }),
  saveNote: (input: SaveNoteInput) => invoke<SaveNoteResponse>("save_note", { input }),
  softDeleteNote: (id: string) => invoke<void>("soft_delete_note", { id }),
  restoreNote: (id: string) => invoke<void>("restore_note", { id }),
  permanentlyDeleteNote: (id: string) => invoke<void>("permanently_delete_note", { id }),
  setNoteArchived: (id: string, archived: boolean) =>
    invoke<Note>("set_note_archived", { id, archived }),
  listCategories: () => invoke<Category[]>("list_categories"),
  createCategory: (name: string, color = "slate") =>
    invoke<Category>("create_category", { name, color }),
  deleteCategory: (id: string) => invoke<void>("delete_category", { id }),
  listTags: () => invoke<Tag[]>("list_tags"),
  deleteTag: (id: string) => invoke<void>("delete_tag", { id }),
  searchNotes: (query: SearchQuery) => invoke<SearchResult[]>("search_notes", { query }),
  getSearchHistory: () => invoke<SearchHistoryItem[]>("get_search_history"),
  clearSearchHistory: () => invoke<void>("clear_search_history"),
  getSettings: () => invoke<AppSettings>("get_settings"),
  updateSettings: (settings: AppSettings) => invoke<void>("update_settings", { settings }),
  analyzeNote: (id: string) => invoke<OrganizerResult>("analyze_note", { id }),
  setOrganizerSuggestionStatus: (id: string, status: "accepted" | "dismissed") =>
    invoke<void>("set_organizer_suggestion_status", { id, status }),
  exportJson: (path: string) => invoke<void>("export_json", { path }),
  exportMarkdown: (directory: string) => invoke<number>("export_markdown", { directory }),
  previewImport: (path: string) => invoke<ImportPreview>("preview_import", { path }),
  importJson: (path: string) => invoke<ImportResult>("import_json", { path }),
  createBackup: (path: string) => invoke<BackupManifest>("create_backup", { path }),
  restoreBackup: (path: string) => invoke<string>("restore_backup", { path }),
  showQuickWindow: (createNew = false) => invoke<void>("show_quick_window", { createNew }),
  toggleQuickWindow: () => invoke<void>("toggle_quick_window"),
  hideQuickWindow: () => invoke<void>("hide_quick_window"),
  hideMainWindow: () => invoke<void>("hide_main_window"),
  showMainWindow: (noteId?: string | null) => invoke<void>("show_main_window", { noteId }),
  quitApp: () => invoke<void>("quit_app"),
  databaseInfo: () => invoke<{ path: string; fts5: boolean }>("database_info"),
};
